language: cpp
env:
  global:
  - CCACHE_CPP2=1
  - CCACHE_DISABLE=1
  - JOBS=4
  - QT_FATAL_WARNINGS=1
  - SHADOW_BUILD_DIR=/tmp/shadow_build_dir
matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    env: SPEC=linux-g++-64 CONFIG=installer
    sudo: required
  - os: linux
    dist: trusty
    env: SPEC=linux-g++-64 CONFIG=debug
    sudo: required
  - os: osx
    osx_image: xcode8
    env: SPEC=macx-clang CONFIG=installer
    sudo: required
addons:
  apt:
    packages:
    - ccache
    - espeak
    - libespeak-dev
    - libgstreamer-plugins-base1.0-dev
    - libgstreamer1.0-0:amd64
    - libgstreamer1.0-dev
    - libsdl2-dev
    - libudev-dev
    - wget
cache:
  directories:
  - "$HOME/.ccache"
before_install:
- if [ "${CONFIG}" = "installer" ]; then cd ${TRAVIS_BUILD_DIR} && git fetch --unshallow
  && git fetch --all --tags; fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then wget https://s3.amazonaws.com/px4-travis/toolchain/macos/ccache
  && chmod +x ccache && sudo mv ccache /usr/local/bin; fi
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export JOBS=$((`cat /proc/cpuinfo | grep
  -c ^processor`+1)); elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then export JOBS=$((`sysctl
  -n hw.ncpu`+1)); fi
install:
- if [ "${SPEC}" = "linux-g++-64" ]; then wget https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.7.1-linux-min.tar.bz2
  && tar jxf Qt5.7.1-linux-min.tar.bz2 -C /tmp && export PATH=/tmp/Qt5.7-linux/5.7/gcc_64/bin:$PATH
  && export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start ; fi
- if [ "${SPEC}" = "macx-clang" ]; then wget https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.7.1-mac-clang-min.tar.bz2
  && tar jxf Qt5.7.1-mac-clang-min.tar.bz2 -C /tmp && wget https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/gstreamer-1.0-1.5.2-x86_64.pkg
  && sudo installer -verboseR -pkg gstreamer-1.0-1.5.2-x86_64.pkg -target / && wget
  https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/gstreamer-1.0-devel-1.5.2-x86_64.pkg
  && sudo installer -verboseR -pkg gstreamer-1.0-devel-1.5.2-x86_64.pkg -target /
  && wget https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/osx-gstreamer.tar.bz2
  && sudo tar jxf osx-gstreamer.tar.bz2 -C /Library/Frameworks && export QT_DIR=Qt5.7-mac-clang/5.7/clang_64
  && export QT_QPA_PLATFORM_PLUGIN_PATH=/tmp/$QT_DIR/plugins && export QML2_IMPORT_PATH=/tmp/$QT_DIR/qml
  && export PATH=/tmp/$QT_DIR/bin:$PATH ; fi
before_script:
- cd ${TRAVIS_BUILD_DIR}
- wget http://px4-travis.s3.amazonaws.com/Firmware/master/parameters.xml -O src/FirmwarePlugin/PX4/PX4ParameterFactMetaData.xml
- wget http://px4-travis.s3.amazonaws.com/Firmware/master/airframes.xml -O src/AutoPilotPlugins/PX4/AirframeFactMetaData.xml
script:
- mkdir ${SHADOW_BUILD_DIR} && cd ${SHADOW_BUILD_DIR}
- qmake -r ${TRAVIS_BUILD_DIR}/qgroundcontrol.pro CONFIG+=${CONFIG} CONFIG+=WarningsAsErrorsOn
  -spec ${SPEC}
- if [ "${SPEC}" != "macx-ios-clang" ]; then make -j$JOBS; else xcodebuild -IDEBuildOperationMaxNumberOfConcurrentCompileTasks=$JOBS
  -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  -c && $(exit ${PIPESTATUS[0]}); fi
- if [[ "${SPEC}" = "linux-g++-64" && "${CONFIG}" = "debug" ]]; then mkdir -p ~/.config/QtProject/
  && cp ${TRAVIS_BUILD_DIR}/test/qtlogging.ini ~/.config/QtProject/ && ./debug/qgroundcontrol-start.sh
  --unittest; fi
after_success:
- cd ${TRAVIS_BUILD_DIR}
before_deploy:
- cd ${TRAVIS_BUILD_DIR}
- if [[ "${SPEC}" = "linux-g++-64" && "${CONFIG}" = "installer" ]]; then ./deploy/create_linux_appimage.sh
  ${TRAVIS_BUILD_DIR} ${SHADOW_BUILD_DIR}/release ${SHADOW_BUILD_DIR}/release/package;
  fi
deploy:
  provider: releases
  api_key:
    secure: UFakSHWfNRCbCIRsWxOFUsM+9u7d1UesEKmiAzODNVMkaP3cY+LZgYNelhYckXd4hvvzxiqca8qfIlYmozEQM5OA/KgtQS9iNozzufESe7dY/Qrro+SYzs34+MzSJ0bIzI6vMUC3xSaflEu6QAMBQdHjHn/yCk845072OJc17OD5TceTVXryPSxePhrPHhNENmkjyS6BWjJJpb751HBYyrlrH4HG8Sra7ctVmFw2wThPMjRZdST3VEYAZIIhvVzz+Lniiu0lgtJjk2HvMFGTaXkyxnTuxKTdUm2f5IIRd8GVW/aCjZmf/ozF+qa4gpebVdIQv2PMibrHRt0yN3hqlduopWuKrNnLbMIv72PIAqV7waufSXFEWhZhd3XciS6V6Am9fD3gz24fkbhr4z6Rpq9DXwnSFhi/vOeXAH6sPDurahTMv8GhZQQ+5jaGRTpL/RJIqqwrb/GY3yEeR9H/qbMR16mDuGuogrE95p+zrAibdk+v+oGrDnr7bfCHst4ziRouOYxeU2CA4Ee5KO0eXt9BCtpCBCzWNLn8ZW+TWCuRQiPraqbSPY5MhyI3/nXqF1zWvI7iUVeXn7xJzpo7NBJwOh0wQajG/L+vFm6NJJahHIw31ObLXZZJDlzsCADnRlGjW9Uw7MOWfTEi6HkJLMxybNO0g0Ucd9etysjgVtE=
  file_glob: true
  file:
  - ${SHADOW_BUILD_DIR}/release/package/qgroundcontrol.*
  - ${SHADOW_BUILD_DIR}/release/package/QGroundControl.*
  skip-cleanup: true
  on:
    tags: true
    condition: $CONFIG = installer
